# Generated by Django 4.0.1 on 2022-01-27 07:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressId', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
                ('zipcode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('DOB', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('job_titleId', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('job_titleDesc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lesson_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('lessonTitle', models.CharField(max_length=50)),
                ('cost', models.CharField(max_length=5)),
                ('duration', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseType',
            fields=[
                ('licenseTypeId', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('licenseTypeDesc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('requestId', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('startDate', models.DateTimeField()),
                ('DateCreated', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('Created_by', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='RequestStatus',
            fields=[
                ('requestStatusId', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('requetstatusdesc', models.CharField(max_length=5)),
                ('is_active', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation_status',
            fields=[
                ('reservationStatusId', models.IntegerField(max_length=5, primary_key=True, serialize=False)),
                ('reservationStatusdesc', models.TextField()),
                ('is_active', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('serviceId', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('service_desc', models.TextField()),
                ('cost', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Service_type',
            fields=[
                ('servicetypeId', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('servicetypeDesc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('vehicletypeId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('vehicletypeDesc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicleId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('vehicleModel', models.CharField(max_length=30)),
                ('registrationDetails', models.CharField(max_length=30)),
                ('vehicletypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexApp.vehicletype')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staffId', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('is_active', models.CharField(max_length=3)),
                ('addressId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexApp.address')),
                ('job_titleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexApp.jobtitle')),
            ],
        ),
        migrations.CreateModel(
            name='Service_lesson',
            fields=[
                ('servicelessonId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('lessson_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexApp.lesson')),
                ('serviceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexApp.service')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='service_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexApp.service_type'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservationId', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('lesson_scheduled_date', models.DateTimeField()),
                ('Created_date', models.DateField()),
                ('created_by', models.CharField(max_length=25)),
                ('last_modified_date', models.DateTimeField()),
                ('last_modifiedby', models.CharField(max_length=25)),
                ('Service_lessonId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexApp.service_lesson')),
                ('Vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexApp.vehicle')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexApp.request')),
                ('reservation_statusID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexApp.reservation_status')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexApp.staff')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='RequestStatusId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexApp.requeststatus'),
        ),
        migrations.AddField(
            model_name='request',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexApp.customer'),
        ),
        migrations.AddField(
            model_name='request',
            name='vehicleTypeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexApp.vehicletype'),
        ),
        migrations.AddField(
            model_name='customer',
            name='License_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexApp.licensetype'),
        ),
    ]
