# Generated by Django 4.0.1 on 2022-01-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation_status',
            name='reservationStatusId',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
