# Generated by Django 4.0.1 on 2022-02-12 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0003_remove_staff_addressid_alter_customer_customer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_id',
            new_name='id',
        ),
    ]
