# Generated by Django 4.0.1 on 2022-02-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0005_alter_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtitle',
            name='job_titleDesc',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
