# Generated by Django 4.0.1 on 2022-02-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0007_staff_id_alter_staff_staffid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation_status',
            old_name='reservationStatusId',
            new_name='reservation_statusId',
        ),
        migrations.RemoveField(
            model_name='request',
            name='RequestStatusId',
        ),
        migrations.RemoveField(
            model_name='requeststatus',
            name='requestStatusId',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_statusID',
        ),
        migrations.RemoveField(
            model_name='service',
            name='serviceId',
        ),
        migrations.RemoveField(
            model_name='service_lesson',
            name='servicelessonId',
        ),
        migrations.RemoveField(
            model_name='service_type',
            name='servicetypeId',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicleId',
        ),
        migrations.AddField(
            model_name='requeststatus',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service_lesson',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service_type',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservationId',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='vehicletypeDesc',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
