# Generated by Django 4.0.1 on 2022-02-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0007_staff_id_alter_staff_staffid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletype',
            name='vehicletypeDesc',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
