# Generated by Django 4.0.1 on 2022-02-15 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indexApp', '0007_staff_id_alter_staff_staffid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateCreated', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexApp.customer')),
                ('license_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexApp.licensetype')),
            ],
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='Service_lessonId',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='Vehicle_id',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='request_id',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_statusID',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='staff_id',
        ),
        migrations.RenameField(
            model_name='reservation_status',
            old_name='reservationStatusId',
            new_name='reservation_statusId',
        ),
        migrations.RemoveField(
            model_name='requeststatus',
            name='requestStatusId',
        ),
        migrations.RemoveField(
            model_name='service',
            name='serviceId',
        ),
        migrations.RemoveField(
            model_name='service_lesson',
            name='servicelessonId',
        ),
        migrations.RemoveField(
            model_name='service_type',
            name='servicetypeId',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicleId',
        ),
        migrations.AddField(
            model_name='requeststatus',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service_lesson',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service_type',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='vehicletypeDesc',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
