# Generated by Django 4.0.1 on 2022-02-15 11:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indexApp', '0008_application_remove_reservation_service_lessonid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreatedDate', models.DateTimeField(verbose_name=datetime.datetime(2022, 2, 15, 11, 52, 32, 921737, tzinfo=utc))),
                ('startDate', models.DateTimeField()),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ServiceLessonId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexApp.lesson')),
                ('StaffId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexApp.staff')),
                ('applicationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexApp.application')),
                ('vehicleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexApp.vehicle')),
            ],
        ),
    ]
