# Generated by Django 4.0.1 on 2022-02-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0008_alter_vehicletype_vehicletypedesc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requeststatus',
            name='requestStatusId',
        ),
        migrations.RemoveField(
            model_name='reservation_status',
            name='reservationStatusId',
        ),
        migrations.RemoveField(
            model_name='service',
            name='serviceId',
        ),
        migrations.RemoveField(
            model_name='service_lesson',
            name='servicelessonId',
        ),
        migrations.RemoveField(
            model_name='service_type',
            name='servicetypeId',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicleId',
        ),
        migrations.AddField(
            model_name='requeststatus',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation_status',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service_lesson',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service_type',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
