# Generated by Django 4.0.1 on 2022-02-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0009_remove_requeststatus_requeststatusid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation_status',
            name='id',
        ),
        migrations.AddField(
            model_name='reservation',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation_status',
            name='reservation_statusId',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservationId',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
