# Generated by Django 4.0.1 on 2022-02-21 21:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indexApp', '0009_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='License_type',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='CreatedDate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 2, 21, 21, 29, 58, 883719, tzinfo=utc)),
        ),
    ]
