# Generated by Django 4.0.1 on 2022-02-21 21:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indexApp', '0011_alter_reservation_createddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='CreatedDate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 2, 21, 21, 34, 14, 154411, tzinfo=utc)),
        ),
    ]
