# Generated by Django 4.0.1 on 2022-08-22 18:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0014_customer_category_staff_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='username',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='CreatedDate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 8, 22, 18, 42, 26, 726857, tzinfo=utc)),
        ),
    ]
