# Generated by Django 4.0.1 on 2022-08-22 19:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0016_vehicle_image_alter_reservation_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='CreatedDate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 8, 22, 19, 39, 27, 388136, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(default='static/images/default.jpg', upload_to='images'),
        ),
    ]
