# Generated by Django 4.0.1 on 2022-08-23 05:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0018_student_remove_application_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default='Driving', max_length=30),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='CreatedDate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 8, 23, 5, 3, 16, 285854, tzinfo=utc)),
        ),
    ]
