# Generated by Django 4.0.1 on 2022-09-03 19:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indexApp', '0019_student_course_alter_reservation_createddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='Author',
        ),
        migrations.AlterField(
            model_name='application',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='CreatedDate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 3, 19, 59, 49, 848132, tzinfo=utc)),
        ),
    ]
