# Generated by Django 4.0.1 on 2022-09-03 21:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0020_remove_application_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='CreatedDate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 3, 21, 6, 8, 255485, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='carimage'),
        ),
    ]
