# Generated by Django 4.0.1 on 2022-09-04 06:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0021_alter_reservation_createddate_alter_vehicle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensetype',
            name='Duration',
            field=models.CharField(default='1 month', max_length=30),
        ),
        migrations.AddField(
            model_name='licensetype',
            name='Fee',
            field=models.CharField(default='0.00', max_length=5),
        ),
        migrations.AddField(
            model_name='licensetype',
            name='category',
            field=models.CharField(default='moped', max_length=30),
        ),
        migrations.AlterField(
            model_name='licensetype',
            name='licenseTypeDesc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='CreatedDate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 4, 6, 25, 57, 745170, tzinfo=utc)),
        ),
    ]
