# Generated by Django 4.0.1 on 2022-09-04 06:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0022_licensetype_duration_licensetype_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensetype',
            name='Type',
            field=models.CharField(default='moped', max_length=30),
        ),
        migrations.AlterField(
            model_name='licensetype',
            name='category',
            field=models.CharField(default='Category A1', max_length=30),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='CreatedDate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 4, 6, 29, 33, 249261, tzinfo=utc)),
        ),
    ]
