# Generated by Django 4.0.1 on 2022-09-04 07:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0023_licensetype_type_alter_licensetype_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='DateCreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='CreatedDate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 4, 7, 21, 16, 74877, tzinfo=utc)),
        ),
    ]
