# Generated by Django 4.0.1 on 2022-09-05 21:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0024_alter_application_datecreated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensetype',
            name='Duration',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='licensetype',
            name='Fee',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='licensetype',
            name='Type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='licensetype',
            name='category',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='CreatedDate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 5, 21, 43, 34, 200340, tzinfo=utc)),
        ),
    ]
