# Generated by Django 2.2.5 on 2022-09-08 07:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0026_auto_20220908_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='CreatedDate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 8, 7, 8, 28, 18239, tzinfo=utc)),
        ),
    ]
