# Generated by Django 2.2.5 on 2022-09-08 07:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('indexApp', '0027_auto_20220908_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='CreatedDate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 8, 7, 44, 7, 341696, tzinfo=utc)),
        ),
    ]
